Models/EmailDTO.cs
namespace DivulgueSuaPesquisa.Models;

public class EmailDTO
{
    public string Subject { get; set; } = string.Empty;
    public string Body { get; set; } = string.Empty;
}

Models/EmailDto.cs
using System.ComponentModel.DataAnnotations;

namespace DivulgueSuaPesquisa.Models;

public class EmailDto
{
    public string? Subject { get; set; }
    
    [Required]
    public string? Name { get; set; }
    
    public string? Lab { get; set; }
    
    [Required]
    public string? Dept { get; set; }
    
    [Required]
    public string? ResearchTitle { get; set; }
    
    [Required]
    public string? ResearchSummary { get; set; }
    
    [Required]
    public string? PublicationLink { get; set; }
    
    [Required]
    public string? ContactPhone { get; set; }
    
    [Required]
    [EmailAddress(ErrorMessage = "O formato do e-mail não é válido.")]
    public string? ContactEmail { get; set; }
}

Controllers/EmailController.cs
using DivulgueSuaPesquisa.Models;
using DivulgueSuaPesquisa.Services.EmailService;
using Microsoft.AspNetCore.Mvc;

namespace DivulgueSuaPesquisa.Controllers;

[Route("[controller]")]
public class EmailController : Controller
{
    private readonly IEmailService _emailService;

    public EmailController(IEmailService emailService)
    {
        _emailService = emailService;
    }

    [HttpPost]
    [Route("SendEmail")]
    public IActionResult SendEmail([FromBody] EmailDto request)
    {
        _emailService.SendEmail(request);
        return Ok();
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace DivulgueSuaPesquisa.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Divulgue sua pesquisa na Agência UFC";
}

<header class="mb-4 text-center" xmlns="http://www.w3.org/1999/html">
    <div class="mt-4">
        <img src="assets/agenciaufc_header_logo.png" alt="Logo da Agência UFC"/>
    </div>
</header>

<body>
    <div class="container">
        <!-- Dropdown 1 -->
        <div class="row justify-content-center mb-2">
            <div class="col-md-6 text-center mb-2">
                <div class="dropdown custom-dropdown">
                    <button class="btn btn-secondary dropdown-toggle small-font" type="button"
                            id="agenciaDropdown" data-bs-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        O que é a Agência UFC?
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="agenciaDropdown">
                        <li>
                            <p class="dropdown-item-text">
                                A Agência UFC é um canal focado na divulgação de pesquisas científicas desenvolvidas na Universidade Federal do Ceará. <br>
                                <br>
                                Nosso objetivo é tornar o conhecimento científico disponível a toda a sociedade, auxiliando a UFC a cumprir seu papel como entidade de caráter público. <br>
                                <br>
                                É por isso que todas as nossas matérias são ficam disponíveis à utilização pela imprensa (com os devidos créditos), para que as pesquisas sejam amplamente divulgadas.<br> 
                                <br>
                                O gerenciamento da Agência UFC está a cargo da Secretaria de Comunicação e Marketing da UFC.
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Dropdown 2 -->
        <div class="row justify-content-center mb-2">
            <div class="col-md-6 text-center mb-2">
                <div class="dropdown custom-dropdown">
                    <button class="btn btn-secondary dropdown-toggle small-font" type="button"
                            id="critériosDropdown" data-bs-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        Quais os critérios de divulgação?
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="criteriosDropdown">
                        <li>
                            <p class="dropdown-item-text">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. ...
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Dropdown 3 -->
        <div class="row justify-content-center mt-2 mb-4">
            <div class="col-md-12 text-center">
                <div class="dropdown custom-dropdown">
                    <button class="btn btn-secondary dropdown-toggle small-font" type="button"
                            id="processoDropdown" data-bs-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        Como funciona o processo de publicação?
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="processoDropdown">
                        <li>
                            <p class="dropdown-item-text">
                                Nossa equipe de jornalistas irá avaliar a sugestão de pauta e entrar em contato com a pessoa responsável pela pesquisa para iniciar o processo de produção.<br>
                                <br>
                                Existem alguns passos até a publicação da matéria:<br>
                                - Entrevista com pesquisadores.<br>
                                - Redação do texto;<br>
                                - Revisão técnica por parte do(a) pesquisador(a);<br>
                                - Revisão final;<br>
                                - Publicação no site da Agência UFC, no portal da UFC e nas mídias sociais;<br>
                                - Envio de matéria para a imprensa.
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <form id="emailForm" method="post" asp-controller="Email" asp-action="SendEmail">
            <div class="row">
                <div class="mb-3 col-md-6">
                    <label for="name" class="form-label">Responsável pela pesquisa:</label>
                    <input type="text" class="form-control" id="name" name="name" required>
                </div>
                <div class="mb-3 col-md-6">
                    <label for="lab" class="form-label">Laboratório:</label>
                    <input type="text" class="form-control" id="lab" name="lab">
                </div>
            </div>
            <div class="row">
                <div class="mb-3 col-md-6">
                    <label for="dept" class="form-label">Departamento ou Programa de Pós-Graduação:</label>
                    <input type="text" class="form-control" id="dept" name="dept" required>
                </div>
                <div class="mb-3 col-md-6">
                    <label for="publicationLink" class="form-label">Link de publicação:</label>
                    <input type="text" class="form-control" id="publicationLink" name="publicationLink">
                </div>
            </div>
            <div class="row">
                <div class="mb-3 col-md-6">
                    <label for="contactPhone" class="form-label">Telefone de contato:</label>
                    <input type="tel" class="form-control" id="contactPhone" name="contactPhone" required>
                </div>
                <div class="mb-3 col-md-6">
                    <label for="contactEmail" class="form-label">E-mail de contato:</label>
                    <input type="email" class="form-control"
                           id="contactEmail" name="contactEmail"
                           pattern="[a-z0-9._%+-]+@@[a-z0-9.-]+\.[a-z]{2,}$"
                           title="Informe um endereço de e-mail válido. Exemplo: usuario@dominio.com"
                           required>
                    <div class="invalid-feedback">
                        Por favor, insira um endereço de e-mail válido.
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="researchTitle" class="form-label">Título da pesquisa:</label>
                <input type="text" class="form-control" id="researchTitle" name="researchTitle" required>
            </div>
            <div class="mb-3">
                <label for="researchSummary" class="form-label">Resumo da pesquisa:</label>
                <textarea class="form-control" id="researchSummary" name="researchSummary" rows="4" required
                          placeholder="Não é necessário incluir tudo (teremos a entrevista para isso), mas inclua as informações importantes sobre a pesquisa, como objetivos e resultados."></textarea>
            </div>
            <div class="row">
                <div class="mb-3 col-md-12 form-check">
                    <input type="checkbox" class="form-check-input" id="checkbox1" required>
                    <label class="form-check-label" for="checkbox1">
                        Concordo que minha pesquisa seja divulgada nos canais
                        da UFC Informa (Agência UFC, portal e mídias sociais).
                    </label>
                </div>
                <div class="mb-3 col-md-12 form-check">
                    <input type="checkbox" class="form-check-input" id="checkbox2" required>
                    <label class="form-check-label" for="checkbox2">
                        Estou ciente de que pode haver interesse da imprensa na
                        pesquisa e concordo em fornecer meu contato a eventuais
                        jornalistas interessados na criação de matérias de circulação nacional.
                    </label>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="mb-3 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary" id="submitButton" disabled>Enviar</button>
                </div>
            </div>
        </form>
    </div>
    
    <!-- Modals -->
    <div class="modal" tabindex="-1" role="dialog" id="successModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">E-mail enviado com sucesso!</h5>
                </div>
                <div class="modal-body">
                    Recebemos o seu e-mail e entraremos em contato em até 3 dias.<br/>
                    <br/>
                    Caso não tenha resposta nesse tempo, você pode entrar em contato conosco: coordenacao.ufcinforma@ufc.br ou (85) 3366 7331.
                </div>
            </div>
        </div>
    </div>
    <div class="modal" tabindex="-1" role="dialog" id="errorModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Falha no envio do e-mail!</h5>
                </div>
                <div class="modal-body">
                    Houve uma falha no envio do e-mail. Por favor, tente novamente.<br/>
                    <br/>
                    Caso continue a ter problemas, entre em contato conosco: coordenacao.ufcinforma@ufc.br ou (85) 3366 7331.
                </div>
            </div>
        </div>
    </div>
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/DivulgueSuaPesquisa.styles.css" asp-append-version="true" /> *@
    
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>

<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="d-flex flex-column align-items-center py-4 my-4 border-top custom-footer">
        <a href="http://www.ufc.br" class="mb-3 link-dark text-decoration-none">
            <img src="assets/ufc_footer_logo.png" alt="UFC Logo" class="img-fluid">
        </a>
    
        <ul class="nav list-unstyled">
            <li class="nav-item"><a href="https://agencia.ufc.br/quem-somos/" class="nav-link px-2 text-white">Quem somos</a></li>
            <li class="nav-item"><a href="https://agencia.ufc.br/use-nossas-materias/" class="nav-link px-2 text-white">Use nossas matérias</a></li>
        </ul>
    
        <p class="mb-0 text-white">&copy; 2024 Universidade Federal do Ceará</p>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/emailForm.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Templates/EmailTemplate.cshtml
@model EmailDto;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@Model.Subject</title>
</head>
<body>
    <h2>@Model.Subject</h2>

    <p><strong>Nome:</strong> @Model.Name</p>
    <p><strong>Laboratório:</strong> @Model.Lab</p>
    <p><strong>Departamento ou Programa de Pós-Graduação:</strong> @Model.Dept</p>
    <p><strong>Título da pesquisa:</strong> @Model.ResearchTitle</p>
    <p><strong>Resumo da pesquisa:</strong> @Model.ResearchSummary</p>
    <p><strong>Link de publicação:</strong> @Model.PublicationLink</p>
    <p><strong>Telefone:</strong> @Model.ContactPhone</p>
    <p><strong>E-mail:</strong> @Model.ContactEmail</p>
</body>
</html>